- hosts: hostservers
  become: yes
  become_method: sudo
  remote_user: aswinrprasad
  
  tasks: 
    - name: enable UFW
      ufw:
        state: enabled

    - name: Allow port 8080 
      ufw:
        rule: allow 
        port: 8080
        proto: tcp

    - name: Allow port 22
      ufw: 
        rule: allow
        port: 22
        proto: tcp
        
    - name : Update Sources List
      command: apt-get update
    
    # - name: Install Jdk
    #   apt:
    #     name: openjdk-11-jdk
    #     state: present
    
    - name: Install docker
      package:
        name: docker-ce
        state: present
  
  - name: Start docker service
    service:
      name: docker
      state: started

  - name: Pull the React App from dockerhub
    docker_image:
      name: aswinrprasad/jenkins-trigger-web
  